### ISSUE TITLE
ESMに対応する

### ISSUE THREAD

**Issue by yy0931** [yy0931/nadesiko3-vscode#12]
- VSCodeの拡張機能はcjsで書くことが必須になっている。
- esbuildかなにかでesmをcjsに変換できるはず。

**Comment by yy0931** [comment]
取り込み命令が機能しない。
NakoCompiler.addPlugin 内からエラーが飛ぶ。po["activate"] がオブジェクトではなく関数になっているせい。
それ以外は正常に動作する。

**Comment by yy0931** [comment]
もしかして `！「plugin_csv.mjs」を取り込む` に仕様変更されている？

**Comment by kujirahand** [comment]
上記の点、ESM対応におけるプラグインの取り込みで、拡張子の明示が必須になってしまいました(T_T)

**Comment by yy0931** [comment]
- [1.21.3](https://github.com/yy0931/nadesiko3-vscode/commit/5bfac58b79324bdac16e9bd879cb051f0b256ee6) で対応が完了した。
- dynamic import を使ったcjsからのesmの呼び出しが、デバッグ実行ではうまく行くのに、拡張機能をパッケージ化するとvscode-loaderのせいで `A dynamic import callback was not specified.` と `Invalid host defined options` が飛ぶようになる問題 (参照: https://github.com/microsoft/vscode/issues/130367#issuecomment-1030406179) を解決できず、諦めてnadesiko3のソースコード全体をcjsに変換した。~~が、https://github.com/microsoft/vscode/issues/130367#issuecomment-1098687465 の言うように esm パッケージを使っても良かったかも。~~

追記: https://stackoverflow.com/questions/71927205/how-to-use-get-port-package-from-a-vs-code-extension がesmパッケージを使ってみて動かなかったと言っている。公開されていたコードを手元で動かしてみたが、確かに動かない。
