### ISSUE TITLE
関数の重複定義の警告が表示されなくなった？

### ISSUE THREAD

**Issue by yy0931** [yy0931/nadesiko3-vscode#7]
以前から表示されていなかった？それともなでしこ言語側の問題か？

```
●階乗とは
ここまで
```

**Comment by kujirahand** [comment]
なでしこ側の問題です。プラグインによって、同じ命令でも命令が作れるように上書きを禁止していません。
なおユーザー定義関数では警告が出ます。

**Comment by yy0931** [comment]
了解です。
